Added support for Alpine
ansible-collections/ansible-consul pull request #377
Opened 2020-02-21 19:47 UTC by coryjthompson

Hello, thank you for the great role.

I had to make a few changes to get this role running correctly on Alpine 3.11. 

- Introduced an Alpine variables file 
- Started using OpenRC for the service init scripts. I was initially modifying the sysvinit script however it ended up having so many "if alpine" blocks that it made more sense to introduce an openrc script.

I had to make a call whether consul_run_path was configurable as in the openrc best practices guide it highly recommends against it. I decided to force to /var/run on alpine to keep it standard and added a note to the readme. 

Let me know if I need to make any improvements.

2020-02-24 21:32 UTC, coryjthompson commented
- Github actions is using molecule schema v2 and travis ci is using molecule schema v3.

Details to why Travis build is failing here:
https://molecule.readthedocs.io/en/latest/configuration.html#lint

2020-03-15 12:21 UTC, bbaassssiiee requested changes
Please add a `molecule/alpineX` scenario so we can test it. Travis build should pass.

2020-03-15 21:37 UTC, bbaassssiiee commented
Travis build should pass.

2022-07-08 09:36 UTC, bbaassssiiee commented
Lack of activity.

2022-07-08 09:36 UTC, closed without merging