Stop sending logs to syslog through systemd
ansible-collections/ansible-consul pull request #393
Opened 2020-05-11 16:10 UTC by smutel

Fix #391

2020-06-06 03:20 UTC, lanefu requested changes
I feel like these lines should only be added to the unit file when `consul_syslog_enable: true`

could you add jinja conditional ?

2020-06-08 19:56 UTC, smutel commented
This is useful in all case:
- When you use consul for log management (consul_syslog_enable: false) => consul will generates logs in his log folder. You don't want to have information twice: in `/var/log/daemon.log` and in `consul_log_path`
- When you use syslog for log management (consul_syslog_enable: false) => consul will use syslog to generate logs. You don't want to have information twice: in `/var/log/daemon.log` and in `consul_log_path`

2020-06-08 22:24 UTC, lanefu approved these changes

2020-06-08 22:25 UTC, merged

2020-06-08 22:25 UTC, lanefu commented
@smutel Thanks for helping me understand.  merged