feat: expose consul limits to custom configuration
ansible-collections/ansible-consul pull request #422
Opened 2020-11-24 15:03 UTC by abarbare

Expose the Consul `limits` with custom configuration https://www.consul.io/docs/agent/options.html#limits

2021-01-11 15:50 UTC, bbaassssiiee commented
Thanks for the PR, due to another merge this now has conflicts. If you drop 3dc3f0f33a32fcc91cee7b32b9f96b43fb407b82 then I think we can rebase this in master.

2021-01-11 15:51 UTC, bbaassssiiee requested changes
Thanks for the PR, due to another merge this now has conflicts. If you drop 3dc3f0f then I think we can rebase this in master.

2021-01-11 15:51 UTC, bbaassssiiee commented on .ansible-lint
> -
Please leave the newline at EOF

2021-01-14 16:23 UTC, abarbare commented on .ansible-lint
> -
Updated 👍

2021-01-18 16:32 UTC, bbaassssiiee approved these changes

2021-01-18 16:33 UTC, merged