distro: add support for Flatcar Linux
ansible-collections/ansible-consul pull request #437
Opened 2021-06-06 13:22 UTC by ahjohannessen

- make systemd unit path configurable as
   Flatcar Linux /lib/systemd/system is read-only.

 - make ansible_python_interpreter configurable depending
   on control host and target host. For instance,
   it can be `/usr/bin/python` on the host and on the target
   it can be `/usr/home/core/bin/python`.

2021-06-06 13:46 UTC, ahjohannessen commented
@bbaassssiiee WDYT?

2021-06-06 13:58 UTC, bbaassssiiee commented
ansible_python_interpreter can best be set in the inventory.
I see too many defines of control_host_ansible_python_interpreter

2021-06-06 13:59 UTC, bbaassssiiee reviewed
Please remove `control_host_ansible_python_interpreter`, you can set it in inventory.

2021-06-06 14:01 UTC, ahjohannessen commented
@bbaassssiiee  `control_host_ansible_python_interpreter` is set because when host is e.g. MacOS the *control host* has path `/usr/bin/python` and the *target host* has, in my case, `/home/core/bin/python` and I have no way of defining a symbolic link to `/usr/bin/python` on Flatcar Linux.

2021-06-06 14:09 UTC, ahjohannessen commented
@bbaassssiiee I think I can solve it as you suggest pr. host. I will test and update the PR 👍

2021-06-06 14:19 UTC, ahjohannessen commented
@bbaassssiiee I have updated the PR as you suggested! It works fine with overriding inventory :)

2021-06-09 07:26 UTC, ahjohannessen commented
@bbaassssiiee Is there anything else I can do in order to get this merged? :)

2021-06-09 16:25 UTC, bbaassssiiee commented
I had to lookup Flatcar Linux, it is supposed to run containers. Why not run consul in a container on it?

2021-06-09 16:47 UTC, ahjohannessen commented
> Why not run consul in a container on it?

Mostly because I can piggy-back on the conventions in this role and to avoid running consul itself in a container as it is not recommended by hashicorp.

2021-06-10 07:11 UTC, bbaassssiiee requested changes
Please fix `vars/Flatcar.yml` to pass yamllint in the GitHub checks.
Bonus: add a Flatcar scenario to **molecule**

2021-06-10 08:20 UTC, ahjohannessen commented
>Please fix vars/Flatcar.yml to pass yamllint in the GitHub checks.
Should be fixed now.

>Bonus: add a Flatcar scenario to molecule
I tried to see how the other scenarios are done, but could not find a suitable image for it.

2021-06-10 08:22 UTC, bbaassssiiee requested changes

2021-06-10 08:22 UTC, bbaassssiiee commented on vars/Flatcar.yml
> +consul_systemd_unit_path: "/etc/systemd/system"
Newline at EOF is missing.

2021-06-10 08:26 UTC, ahjohannessen commented
@bbaassssiiee I think it should be ok now.

2021-06-10 09:06 UTC, ahjohannessen commented
@bbaassssiiee I have added a list of supported *nix distributions in order to avoid lint error with max characters

2021-06-10 09:28 UTC, bbaassssiiee commented
Nice!

2021-06-10 09:29 UTC, bbaassssiiee approved these changes

2021-06-11 06:42 UTC, merged

2021-06-11 07:31 UTC, ahjohannessen commented
:+1: