Improvements for `var-spacing` in ansible-lint
ansible-collections/ansible-consul pull request #541
Opened 2023-03-19 20:57 UTC by ppuschmann

The rule was formerly known as `jinja[spacing]`.

2023-03-20 10:36 UTC, nre-ableton requested changes
Great PR, thanks! :tada: However, before we merge it, please remove the `var-naming` suppression can be removed from `.ansible-lint`.

Thanks! If you don't have time to make the above changes, please let me know and I will fix (and force-push) to your branch.

2023-03-20 10:36 UTC, nre-ableton commented on tasks/install_linux_repo.yml
> +  become: true
This move is technically a fix for `key-order[task]`. I don't necessarily mind it being in this PR, but are you also working on fixing that linter warning?

2023-03-20 10:36 UTC, nre-ableton commented on tasks/main.yml
> +  when: consul_services is defined and consul_services | length>0
```suggestion
  when: consul_services is defined and consul_services | length > 0
```

I wish `ansible-lint` detected this, but it doesn't.

2023-04-03 18:28 UTC, ppuschmann commented on tasks/install_linux_repo.yml
> +  become: true
As far as I can see, this is the last occurence of `key-order[task]`, am I right?

2023-04-04 12:10 UTC, nre-ableton commented
@ppuschmann Thanks for responding to my comments. I'm really busy this week with a project that has a deadline before the Easter holidays, but I'll re-review your changes as soon as I can.

2023-04-05 16:14 UTC, nre-ableton approved these changes
Looks good! I'll merge this as soon as CI goes green. Thanks again for your contribution! 👍

2023-04-05 16:15 UTC, nre-ableton commented on tasks/install_linux_repo.yml
> +  become: true
I haven’t really looked, but I’ll make a separate PR to clean that up.

2023-04-20 15:36 UTC, nre-ableton commented
CI problems have been fixed in https://github.com/ansible-community/ansible-consul/pull/547, but unfortunately that has led to some merge conflicts. Namely, the commit 84bb7cc6e19d0c8ee539262c47983825606152f0 ("Add pipefail to shell-tasks") must be dropped. See further explanation [here](https://github.com/ansible-community/ansible-consul/pull/547#issuecomment-1513570923) as to why we sadly can't use `set -o pipefail`, if you are curious.

So please rebase and drop the commit, and I'll go ahead and merge this PR.

Normally I would rebase this branch myself to save you the trouble, but I don't want to force-push your branch and delete your commits, so I would prefer if you could do it. 👍 If you aren't sure how to rewrite the history and drop the commit, just give me your blessing and I'll take care of it.

2023-08-23 06:15 UTC, closed without merging