Fix rolling restart on Linux
ansible-collections/ansible-consul pull request #598
Opened 2024-05-31 15:55 UTC by 42esoulard

##### SUMMARY

Fixes the rolling restart on Linux in which the the consul service `restart`  was happening too soon after the `consul leave`, which resulted in the playbook proceeding without the new election finalizing and a temporarily leaderless cluster.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- Rolling restart consul on Unix

##### ADDITIONAL INFORMATION
- Since we are using a new variable `consul_pid_file`, it was replaced in all occurrences in the templates as well.

2024-06-03 06:56 UTC, bbaassssiiee commented
Thanks for your contribution! This repo is looking for maintainers...

If feasible, please rebase this PR on master to drop that merge commit. That way we have a linear commit history.

2024-06-03 07:03 UTC, bbaassssiiee requested changes
Please take a look at the output of the checks that ran and amend your PR.

2024-06-03 07:03 UTC, bbaassssiiee commented on tasks/leave_restart_consul.yml
> +  stat:
Please use the FQCN `ansible.builtin.stat`.

2024-06-03 07:03 UTC, bbaassssiiee commented on tasks/leave_restart_consul.yml
> +- block:
Ansible-lint says you can improve the task key order to: when, block. Also please name the block.

2024-06-04 15:08 UTC, estellesoulard commented on tasks/leave_restart_consul.yml
> +  stat:
Done :white_check_mark:

2024-06-04 15:09 UTC, estellesoulard commented on tasks/leave_restart_consul.yml
> +- block:
Done :white_check_mark: thanks :)

2024-06-04 17:52 UTC, bbaassssiiee commented
There is still one linting issue:

```
yaml[indentation]: Wrong indentation: expected 4 but found 2
tasks/leave_restart_consul.yml:12
Error: Wrong indentation: expected 4 but found 2

WARNING  The following filters were mocked during the run: json_query
Read documentation for instructions on how to ignore specific rule violations.

                Rule Violation Summary                
 count tag               profile rule associated tags 
     1 yaml[indentation] basic   formatting, yaml     
```

2024-06-04 17:59 UTC, bbaassssiiee commented
Would you have time to also remove the directory `./molecule/centos-stream-8`?
Centos 8 Stream End-of-life happened to happen 4 days ago (31 May 2024) [https://endoflife.date/centos-stream](https://endoflife.date/centos-stream)

2024-06-06 20:52 UTC, bbaassssiiee approved these changes
Great work!

2024-06-06 20:52 UTC, merged