Multi datacenter support
ansible-collections/ansible-consul pull request #66
Opened 2017-05-07 20:50 UTC by groggemans

Adds some extra internal variables to differentiate between lan servers and wan servers. This allows for basic multi-datacenter support.

Hosts in the same group will use the same encryption key. Defining multiple datacenters in the same group results in multiple auto joining datacenters.

2017-05-07 20:53 UTC, groggemans commented
I've tested this with bootstrap-expect, but I forgot something for bootstrapping with the default bootstrap option. (It still checks for max 1 bootstrap server over all servers) I'll make some modifications to fix this.

2017-05-07 21:08 UTC, groggemans commented
After that last commit it should work for both bootstrap options.

2017-05-07 21:51 UTC, brianshumate requested changes
Awesome, this looks great after the one little style fix.

Thanks!

2017-05-07 21:51 UTC, brianshumate commented on templates/config_server.json.j2
> +    "bootstrap_expect": {{ _consul_lan_servers|length }},
Minor thing, but can you add a spaces on either side of the pipe please?

2017-05-08 05:56 UTC, groggemans commented on templates/config_server.json.j2
> +    "bootstrap_expect": {{ _consul_lan_servers|length }},
@brianshumate do you want to have spaces in these cases to?

`{% if _consul_wan_servers|length > 0 -%}`

Or only when the result is not used in an expression?

2017-05-08 06:29 UTC, groggemans commented
I've added the spaces around all pipe symbols/filters.

Also updated the bootstrap and client templates, seems I forgot those. We may want to try to combine them in a single template file to prevent this in the future.

2017-05-08 13:49 UTC, brianshumate commented
👍 Excellent! Thanks again. Gertjan!

2017-05-08 13:49 UTC, merged